theme = "catppuccin_mocha"

# theme = "catppuccin_macchiato"

[editor]
mouse = false
# auto-format = true
# auto-save = true
line-number = "absolute"
cursorline = true
color-modes = true
bufferline = "multiple"
lsp.display-inlay-hints = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["file-encoding", "file-line-ending", "file-type"]
separator = "â”‚"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true

[keys.normal]
[keys.normal."+"]
m = ":run-shell-command make"
c = ":run-shell-command cargo build"
t = ":run-shell-command cargo check"
